version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command: >
      "--config.file=/etc/prometheus/prometheus.yml"
      "--storage.tsdb.retention.time=90d"
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    volumes:
       - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always
